version: '1.0'

services:
  bot:
    build:
      context: .
      dockerfile: ./imei/Dockerfile
    volumes:
      - ./imei:/app/imei
    env_file:
      - .env
    networks:
      - imei_nt 

  database:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - imei_nt

networks:
  imei_nt:
    name: imei_nt 
