version: '1.0'

services:
  bot:
    build:
      context: .
      dockerfile: ./imei/Dockerfile
    volumes:
      - ./imei:/app/imei
      - ./white_list.csv:/app/white_list.csv
    env_file:
      - .env
    networks:
      - imei_nt 


networks:
  imei_nt:
    name: imei_nt 
