[project]
name = "imei"
version = "0.1.0"
description = ""
authors = [
    {name = "Boba",email = "withloveweb7@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "loguru",
    "aiogram",
    "sqlalchemy",
    "asyncpg (>=0.30.0,<0.31.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
